[workspace]
members = [
    "patreon-proxy",
    "sharder",
    "cache",
    "model",
    "common",
    "database",
    "vote_listener",
    "http-gateway",
    "bot-list-updater",
    "server-counter",
    "stats-channel-updater",
    "secure-proxy",
    "image-proxy"
]
