[package]
name = "vote_listener"
version = "0.1.0"
authors = ["rxdn"]
edition = "2018"

[dependencies]
model = { path = "../model" }
actix-web = "3"
actix-rt = "1"
tokio-postgres = "0.5.5"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"