version: 2
jobs:
  build:
    docker:
      - image: rust:buster

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Print cargo version
          command: cargo --version

      - run:
          name: Update archives
          command: apt-get update && apt-get upgrade -y

      - run:
          name: Install build dependencies
          command: apt-get install -y pkg-config build-essential cmake libssl-dev

      - run:
          name: Build debug
          command: cargo build

      - run:
          name: Build release
          command: cargo build --release

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/debug/incremental
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/release/incremental
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - store_artifacts:
          path: ./target/release/patreon-proxy
          destination: patreon-proxy

      - store_artifacts:
          path: ./target/release/public
          destination: public-sharder

      - store_artifacts:
          path: ./target/release/whitelabel
          destination: whitelabel-sharder

      - store_artifacts:
          path: ./target/debug/public
          destination: public-sharder-debug

      - store_artifacts:
          path: ./target/debug/whitelabel
          destination: whitelabel-sharder-debug
