version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.46.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Print cargo version
          command: cargo --version

      - run:
          name: Build
          command: cargo build --release

      - store_artifacts:
          path: ./target/release/patreon-proxy
          destination: patreon-proxy
