version: 2
jobs:
  build:
    docker:
      - image: rust:alpine

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Print cargo version
          command: cargo --version

      - run:
          name: Install build dependencies
          command: apk add musl-dev pkgconfig libssl-dev

      - run:
          name: Build
          command: cargo build --release

      - store_artifacts:
          path: ./target/release/patreon-proxy
          destination: patreon-proxy
